### ISSUE TITLE
Logout not working

### ISSUE THREAD

**Issue by roos-robert** [HomeSharp/Quartz#2]
Logout not working, home screen should redirect automatically if user is logged in.

**Comment by hg222dt** [comment]
Ja, jag såg detta för ett tag sedan. Men det var en lite inkonsekvent bugg, ibladn loggade den ut mig och ibland inte. Fattade inte varför. Får ta tag i den.

**Comment by roos-robert** [comment]
The issue was a timeout causing the app to freeze before logging a user out, resolving now.

**Comment by roos-robert** [comment]
Bug has been fixed.
